### PR TITLE
TIKA-3446 - Support for parsing OneNote when Alternative Encoding Using the File Synchronization via SOAP Over HTTP Protocol

### PR DESCRIPTION
**Pull request by nddipiazza**
# Support parsing OneNote files when downloaded from O365

Previous version of Tika OneNote parser was not able to handle files saved from Office 365 (SharePoint Online, OneDrive).

See section 2.8 of this document
https://interoperability.blob.core.windows.net/files/MS-ONESTORE/%5bMS-ONESTORE%5d.pdf

which describes that MS-ONESTORE documents can be encoded by the following spec: 
https://interoperability.blob.core.windows.net/files/MS-FSSHTTPB/%5bMS-FSSHTTPB%5d.pdf

Now those getting files from the O365 suite will be able to use the OneNote parser. 

# Things to improve later

* Stream instead of use byte array?
* See if we can use this newer parser code for the on-prem documents too to avoid the code bloat?

### CODE REVIEW

**Comment by tballison** [comment]
Creating a TIKA-3446 branch in our repo

**Comment by tballison** [comment]
Working on checkstyle now

**Comment by tballison** [comment]
I've made cosmetic changes to pass checkstyle and forbidden-apis, and I lowercased a bunch of stuff.  I'm going to run some fuzzed files through it and see if I can trigger any problems, and I'm going to run tests multithreaded.

I'd like to normalize some of the metadata properties or use standard ones.  Other than that, is this ready to go if all extra tests look good?

**Comment by tballison** [comment]
Other point... is it ok to change runtime exceptions to TikaExceptions, generally?

**Comment by nddipiazza** [comment]
> Other point... is it ok to change runtime exceptions to TikaExceptions, generally?
Yup.

> I've made cosmetic changes to pass checkstyle and forbidden-apis, and I lowercased a bunch of stuff. I'm going to run some fuzzed files through it and see if I can trigger any problems, and I'm going to run tests multithreaded.

Excellent you are my hero!

> I'd like to normalize some of the metadata properties or use standard ones. Other than that, is this ready to go if all extra tests look good?

Yeah of course. Feel free to make whatever changes you desire.

**Comment by nddipiazza** [comment]
closing this. we opened a new branch in the actual repo instead of my forked repo.
https://github.com/apache/tika/pull/461

**Pull request closed without merging**
