### PR TITLE
Fix for TIKA-2402

### PR DESCRIPTION
**Pull request by ThejanW**
**Support all image formats in Object Recognition REST Parser**
Currently object recognition REST parser only supports parsing jpeg image type. Objective of this task is to add all image format support to it by converting any image into jpeg format at the server's end.

### CODE REVIEW

**Comment by ThejanW** [comment]
@chrismattmann @thammegowda ping!

**Comment by chrismattmann** [comment]
works great!  all tests pass after rebuilding and redeploying docker and `mvn clean install` in `apache:gsoc17` branch:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Tika 1.17-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tika ---
[INFO] Deleting /Users/mattmann/tmp/tika1.16/target
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ tika ---
[INFO] 
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ tika ---
[INFO] 
[INFO] --- forbiddenapis:2.3:check (default) @ tika ---
[INFO] Skipping execution for packaging "pom"
[INFO] 
[INFO] --- forbiddenapis:2.3:testCheck (default) @ tika ---
[INFO] Skipping execution for packaging "pom"
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tika ---
[INFO] Installing /Users/mattmann/tmp/tika1.16/pom.xml to /Users/mattmann/.m2/repository/org/apache/tika/tika/1.17-SNAPSHOT/tika-1.17-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Tika parent ................................. SUCCESS [  1.099 s]
[INFO] Apache Tika core ................................... SUCCESS [ 22.380 s]
[INFO] Apache Tika parsers ................................ SUCCESS [01:47 min]
[INFO] Apache Tika XMP .................................... SUCCESS [  1.566 s]
[INFO] Apache Tika serialization .......................... SUCCESS [  1.246 s]
[INFO] Apache Tika batch .................................. SUCCESS [01:47 min]
[INFO] Apache Tika language detection ..................... SUCCESS [  2.843 s]
[INFO] Apache Tika application ............................ SUCCESS [ 42.368 s]
[INFO] Apache Tika OSGi bundle ............................ SUCCESS [ 16.988 s]
[INFO] Apache Tika translate .............................. SUCCESS [  1.762 s]
[INFO] Apache Tika server ................................. SUCCESS [ 31.478 s]
[INFO] Apache Tika examples ............................... SUCCESS [  5.661 s]
[INFO] Apache Tika Java-7 Components ...................... SUCCESS [  1.698 s]
[INFO] Apache Tika eval ................................... SUCCESS [ 22.306 s]
[INFO] Apache Tika Deep Learning (powered by DL4J) ........ SUCCESS [ 49.321 s]
[INFO] Apache Tika Natural Language Processing ............ SUCCESS [ 21.168 s]
[INFO] Apache Tika ........................................ SUCCESS [  0.021 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:18 min
[INFO] Finished at: 2017-08-09T08:53:58-07:00
[INFO] Final Memory: 213M/1787M
[INFO] ------------------------------------------------------------------------
LMC-053601:tika1.16 mattmann$ 
```

**Comment by ThejanW** [comment]
thank you @chrismattmann :+1:

**Comment by ThejanW** [comment]
@chrismattmann can we merge the gsoc17 branch with master now and make the two branches even? my next PRs are not directly related to these.

**Comment by chrismattmann** [comment]
absolutely! I'll merge now...

**Comment by chrismattmann** [comment]
done!

**Comment by ThejanW** [comment]
thank you @chrismattmann 💯

**Pull request merged**
