### PR TITLE
TIKA-2016  Sentiment Analysis Parser Contributed by amensiko and thammegowda

### PR DESCRIPTION
**Pull request by thammegowda**
This PR is a refresh of work started by @amensiko and left unmerged in #127 

What is supported:
- Sentiment Analysis is powered by OpenNLP
- Model path can be changed to any compatible Open NLP Max Ent model ( to change, update tika config xml)
   - It can be HTTP URL (caching is not supported at the moment, use it for testing only)
   - It can be a file known to class loader (for hadoop /spark users)
   - It can be a file on file system  (for stand alone users)
   - by default, it retrieves a model from USC DataScience's github repo,  trained on netflix dataset of positive negative sentiments

**Test case included?** yes - Checkout SentimentParserTest
**Example Tika Conf included?**  yes - checkout the config file used by the test case.

## How to test?

```bash
$ mvn clean package
$ echo "What a wonderful thought it is that some of the best days of our lives havent happened yet" > test.sent
$ java -jar tika-app/target/tika-app-1.15-SNAPSHOT.jar \
         --config=tika-parsers/src/test/resources/org/apache/tika/parser/sentiment/analysis/tika-config-sentiment-opennlp.xml \
         -m test.sent 
# Output 
Content-Length: 91
Content-Type: application/sentiment
Sentiment: positive
X-Parsed-By: org.apache.tika.parser.CompositeParser
X-Parsed-By: org.apache.tika.parser.sentiment.analysis.SentimentParser
resourceName: test.sent
```

Note: `Sentiment: positive` was added to metadata

#Closes #127 and TIKA-2016

### CODE REVIEW

**Comment by chrismattmann** [comment]
awesome work @thammegowda! The latest version of the Sentiment Analysis Parser includes categorical analysis, which we will want to include at some point, but this is a great start. I will test this (along with my other testing for video stuff) this weekend.

**Comment by thammegowda** [comment]
> The latest version of the Sentiment Analysis Parser includes categorical analysis, which we will want to include at some point, 

I had tried the newer version. The problems faced: The SentimentME models did not work(They have renamed the classes). So we have to retrain models to upgrade the OpenNLP

**Comment by chrismattmann** [comment]
They worked fine using the old openNLP try with that

**Comment by thammegowda** [comment]
1. The categorical datasets links in Datasets page is broken, we have to fix it too. http://irds.usc.edu/SentimentAnalysisParser/datasets.html 
2. The Models page has no models linked, the paths mentioned in the web page doesnt exists in the repo. http://irds.usc.edu/SentimentAnalysisParser/models.html. I am hoping the Categorical analysis (or multi class classifier in simple words) should work simply by changing the `modelPath` parameter in tika config XML (Please give me a link to model, I will test it :+1: ). By default, it uses netflix review dataset binary label model, but changing it is as easy as editing the tika config XML.
3. The OpenNLP API has changed. I upgraded from 1.5.x to 1.6.0, it went fine. However, the latest is 1.7.2, in this version, they renamed `SentimentME` as `DocumentCagetegorizerME`, thus the existing  _sentiment analysis_ models won't work and we are stuck up here until we regenerate models.

**Comment by chrismattmann** [comment]
1. this is the updated path: https://github.com/USCDataScience/SentimentAnalysisParser/tree/master/sentiment-examples We'll fix it first, before committing.
2. check out: https://github.com/USCDataScience/SentimentAnalysisParser/tree/master/sentiment-examples and test it.
3. pinning it to 1.6.0 is fine. We don't need to always depend on the latest version of things :)

**Comment by thammegowda** [comment]
@chrismattmann Please test this, let me know if you find any issues! Thanks

**Comment by chrismattmann** [comment]
Did you get a chance to make the updates @thammegowda

**Comment by thammegowda** [comment]
I thought no further action needed on this PR (looks like I missed something, sorry!)

If it is about the categorical analysis, there are no code changes needed.

Just use this config for `--config=` argument above.
```xml
<properties>
    <parsers>
        <parser class="org.apache.tika.parser.sentiment.analysis.SentimentParser">
            <mime>text/plain</mime>
            <mime>application/sentiment</mime>
            <params>
                <!--This is default <param name="modelPath" type="string">https://raw.githubusercontent.com/USCDataScience/SentimentAnalysisParser/master/sentiment-models/en-netflix-sentiment.bin</param> -->
                <param name="modelPath" type="string">https://raw.githubusercontent.com/USCDataScience/SentimentAnalysisParser/master/sentiment-models/ht-sentiment-categ.bin</param>
                <!--This can also be relative path sentiment-models/en-stanford-sentiment.bin-->
            </params>
        </parser>
    </parsers>
</properties>
```
I tested again now, it worked!
- Users are free to point to any opennlp classifier model they wish to. 
- The `modelPath` can be HTTP URL or local file path or relative path to the classloader.

I thought I handled all the cases with our awesome XML parameter binding feature.

 What did I miss?

**Comment by chrismattmann** [comment]
thanks @thammegowda for testing with the categorical model too. Seems easy enough. I will test tonight thanks

**Comment by chrismattmann** [comment]
OK tested full build with this. Please remember @thammegowda and everyone - test the *full* tika build. Here's the error (the usual didn't add the dependencies to Felix, so we're getting this error ;) ).:

```
[WARNING] Embed-Dependency: clause "opennlp-maxent" did not match any dependencies
[WARNING] Embed-Dependency: clause "jwnl" did not match any dependencies
[INFO] 
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ tika-bundle ---
[INFO] 
[INFO] --- maven-assembly-plugin:2.4.1:single (default) @ tika-bundle ---
[INFO] Copying files to /Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles
[INFO] 
[INFO] --- maven-failsafe-plugin:2.10:integration-test (default) @ tika-bundle ---
[INFO] Failsafe report directory: /Users/mattmann/git/tika-gh/tika-bundle/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.tika.bundle.BundleIT
[main] INFO org.ops4j.pax.exam.spi.DefaultExamSystem - Pax Exam System (Version: 4.10.0) created.
[main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - creating PaxExam runner for class org.apache.tika.bundle.BundleIT
[main] INFO org.ops4j.pax.exam.junit.impl.ProbeRunner - running test class org.apache.tika.bundle.BundleIT
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testBundleSimpleText in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testManifestNoJUnit in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testTesseractParser in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testTikaBundle in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testBundleDetection in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testBundleDetectors in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]

	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testBundleLoaded in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testForkParser in reactor
ERROR: Bundle org.apache.tika.bundle [13] Error starting file:/Users/mattmann/git/tika-gh/tika-bundle/target/test-bundles/tika-bundle.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
[FelixDispatchQueue] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=org.apache.tika.bundle [13]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.tika.bundle [13]: Unable to resolve 13.0: missing requirement [13.0] osgi.wiring.package; (osgi.wiring.package=opennlp.tools.sentiment)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[main] ERROR org.ops4j.pax.exam.nat.internal.NativeTestContainer - Bundle [org.apache.tika.bundle [13]] is not resolved
INFO  running testBundleParsers in reactor
[main] INFO org.ops4j.pax.exam.spi.reactors.ReactorManager - suite finished
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 93.896 sec <<< FAILURE!

Results :

Tests in error: 
  testBundleSimpleText(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testManifestNoJUnit(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testTesseractParser(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testTikaBundle(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testBundleDetection(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testBundleDetectors(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testBundleLoaded(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testForkParser(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser
  testBundleParsers(org.apache.tika.bundle.BundleIT): gave up waiting for service org.apache.tika.parser.Parser

Tests run: 9, Failures: 0, Errors: 9, Skipped: 0

[INFO] 


```

I'll fix it and push the updates to the TG branch and update the PR.

**Comment by thammegowda** [comment]
Thanks, @chrismattmann I will remember to run the complete tests including OSGI/felix for future PRs 👍

**Comment by chrismattmann** [comment]
I'm not stuck and had to email the list. I don't know how to fix the Felix issue.

**Comment by chrismattmann** [comment]
OK i fixed it :) 👍 going to run tests now and if it passes, I'll commit.

**Comment by chrismattmann** [comment]
BTW this page was a great help http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

**Comment by chrismattmann** [comment]
## Build passes:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Tika 1.15-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tika ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ tika ---
[INFO] 
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ tika ---
[INFO] 
[INFO] --- forbiddenapis:2.2:check (default) @ tika ---
[INFO] Skipping execution for packaging "pom"
[INFO] 
[INFO] --- forbiddenapis:2.2:testCheck (default) @ tika ---
[INFO] Skipping execution for packaging "pom"
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tika ---
[INFO] Installing /Users/mattmann/git/tika-gh/pom.xml to /Users/mattmann/.m2/repository/org/apache/tika/tika/1.15-SNAPSHOT/tika-1.15-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Tika parent ................................. SUCCESS [  1.047 s]
[INFO] Apache Tika core ................................... SUCCESS [ 22.697 s]
[INFO] Apache Tika parsers ................................ SUCCESS [03:23 min]
[INFO] Apache Tika XMP .................................... SUCCESS [  1.649 s]
[INFO] Apache Tika serialization .......................... SUCCESS [  1.436 s]
[INFO] Apache Tika batch .................................. SUCCESS [01:50 min]
[INFO] Apache Tika language detection ..................... SUCCESS [  3.730 s]
[INFO] Apache Tika application ............................ SUCCESS [ 32.442 s]
[INFO] Apache Tika OSGi bundle ............................ SUCCESS [ 17.231 s]
[INFO] Apache Tika translate .............................. SUCCESS [  1.825 s]
[INFO] Apache Tika server ................................. SUCCESS [ 35.426 s]
[INFO] Apache Tika examples ............................... SUCCESS [  9.609 s]
[INFO] Apache Tika Java-7 Components ...................... SUCCESS [  1.738 s]
[INFO] Apache Tika eval ................................... SUCCESS [ 24.480 s]
[INFO] Apache Tika ........................................ SUCCESS [  0.022 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:48 min
[INFO] Finished at: 2017-05-03T13:03:29-07:00
[INFO] Final Memory: 164M/1530M
[INFO] ------------------------------------------------------------------------
LMC-053601:tika-gh mattmann$ 
```

I also tried it myself on the following file:

`sample.sent`
``` 
Man I'm so tired of battling against OSGI!
```

`sample2.sent`
```
Whatever, I need some cooling off time!
```

# Binary sentiment
```
LMC-053601:tika-gh mattmann$ java -jar tika-app/target/tika-app-1.15-SNAPSHOT.jar \
>          --config=tika-parsers/src/test/resources/org/apache/tika/parser/sentiment/analysis/tika-config-sentiment-opennlp.xml \
>          -m sample.sent
WARN  JBIG2ImageReader not loaded. jbig2 files will be ignored
INFO  Sentiment Model is at https://raw.githubusercontent.com/USCDataScience/SentimentAnalysisParser/master/sentiment-models/en-netflix-sentiment.bin
Content-Length: 43
Content-Type: application/sentiment
Sentiment: negative
X-Parsed-By: org.apache.tika.parser.CompositeParser
X-Parsed-By: org.apache.tika.parser.sentiment.analysis.SentimentParser
resourceName: sample.sent
LMC-053601:tika-gh mattmann$ 
```

# Categorical (multi-class sentiment)
Changing to use `sample2.sent`

```
LMC-053601:tika-gh mattmann$ java -jar tika-app/target/tika-app-1.15-SNAPSHOT.jar          --config=tika-parsers/src/test/resources/org/apache/tika/parser/sentiment/analysis/tika-config-sentiment-opennlp-cat.xml          -m sample2.sent
WARN  JBIG2ImageReader not loaded. jbig2 files will be ignored
INFO  Sentiment Model is at https://raw.githubusercontent.com/USCDataScience/SentimentAnalysisParser/master/sentiment-models/ht-sentiment-categ.bin
Content-Length: 39
Content-Type: application/sentiment
Sentiment: angry
X-Parsed-By: org.apache.tika.parser.CompositeParser
X-Parsed-By: org.apache.tika.parser.sentiment.analysis.SentimentParser
resourceName: sample2.sent
LMC-053601:tika-gh mattmann$ 
```

**Comment by thammegowda** [comment]
@chrismattmann 💯  :1st_place_medal:  
Great work

**Comment by chrismattmann** [comment]
added a test for categorical sentiment too thanks @thammegowda and @amensiko !

**Pull request merged**
