### PR TITLE
TIKA-1354 Add test method with nonfunctional fork parser

### PR DESCRIPTION
**Pull request by hlavki**
There is something wrong with pax commons logging so ForkParser doesn't work in general.
Test method: testForkParserPdf()

I suppose that this pull request will never be merged to trunk.

### CODE REVIEW

**Comment by chrismattmann** [comment]
Got it @hlavki . Can you submit an update to this pull request that implements the revert and we'll try that?

**Comment by chrismattmann** [comment]
ping @hlavki any interest in closing this out?

**Comment by hlavki** [comment]
I am working on it

**Comment by hlavki** [comment]
Pull request created https://github.com/apache/tika/pull/30

**Pull request closed without merging**
