### PR TITLE
[TIKA-3948] start moving to Jakarta

### PR DESCRIPTION
**Pull request by solomax**
@tballison the build is RED and it would be hard to fix this :(

The problem is `org.apache.sis*` hardly uses `jaxb-runtime` `2.3.3` (which is NOT compatible with `4.0.3`)

I'm afraid we should contact Apache SIS :)

### CODE REVIEW

**Comment by tballison** [comment]
I guess this didn't go far enough? https://issues.apache.org/jira/browse/SIS-469

**Comment by tballison** [comment]
I asked over on the user list at sis: https://lists.apache.org/thread/5y5wjhjy2kjjfmhyp6jz1komg4fhnjv4

**Comment by desruisseaux** [comment]
Hello all. As answered on the mailing list, SIS 1.4 already migrated to Jakarta 4.0 on the development branch. I was thinking to propose a release in the next few weeks, in an attempt to have it for Halifax conference. Would it fit your schedule?

**Comment by tballison** [comment]
Y, that'd be great!  Thank you so much!  See you in Halifax?

**Comment by desruisseaux** [comment]
Yes, I will be there all 4 days. See you there!

**Pull request merged**
