### PR TITLE
add applyProbabilitySelection mechanism

### PR DESCRIPTION
**Pull request by LukeLiush**
https://issues.apache.org/jira/browse/TIKA-1517
Please refer to the details of the feature in the above JIRA issue.
The prototype 1.

### CODE REVIEW

**Comment by LukeLiush** [comment]
found another error in at the line of code that check the threshold.
 	maxProb < threshold ? this.rootMimeType : bestEstimate;

**Comment by grossws** [comment]
Can you reformat code to Tika style to avoid rewritting all the file? It's hard to distinguish changes from reformatting currently.

**Comment by chrismattmann** [comment]
agreed @grossws , @LukeLiush can you please reformat the code? I'm not sure exactly what changed.

**Comment by LukeLiush** [comment]
@grossws , @chrismattmann 
Hi,
I think i closed this request, and recreate another same pull request where the code has been reformatted.
Please kindly let me know if you are able to view the second request.

**Pull request closed without merging**
