### PR TITLE
add applyProbabilities mechanism

### PR DESCRIPTION
**Pull request by LukeLiush**
reformat code for change

### CODE REVIEW

**Comment by LukeLiush** [comment]
https://issues.apache.org/jira/browse/TIKA-1517

**Comment by LukeLiush** [comment]
@chrismattmann 
@grossws
Hi, i reformatted the code for change, please kindly let me know if you are able to view the change.

**Comment by LukeLiush** [comment]
@Lukeliush
Test

**Comment by chrismattmann** [comment]
Thanks @LukeLiush - I have an idea here. How about you create a sub-class of MimeTypes called BayesianMimeTypes and then override the methods with what you need? Also no need to put comments with /* [luke] */ etc. in there

**Comment by LukeLiush** [comment]
Hi @chrismattmann , thanks a lot for following this up.
I thought about sublcassing MimeTypes when i was implementing it, but I saw that the MimeTypes in the development/trunk version is defined to be a "final" class like the String class which is not extendable...

I will get rid of the [Luke]....:)

**Pull request closed without merging**
