### PR TITLE
fix for TIKA-1787 contributed by Yueheng He

### PR DESCRIPTION
**Pull request by TaichiHo**
Succeed in building using java 1.8.0_65. 
To see the effect, create a text file like the following. 
```
Good afternoon Rajat Raina, how are you today? Hi, I am Tom Brady. I go to school at Stanford University, which is located in California.
```
Save it as test.ner and feed it to tika. 
```
java -classpath tika-app/target/tika-app-1.12-SNAPSHOT.jar org.apache.tika.cli.TikaCLI -m test.ner
```
The result should look like this
```
Content-Length: 137
Content-Type: application/stanford-ner
LOCATION: [California]
ORGANIZATION: [Stanford University]
PERSON: [Rajat Raina, Tom Brady]
X-Parsed-By: org.apache.tika.parser.DefaultParser
X-Parsed-By: org.apache.tika.parser.stanfordNer.StanfordNerParser
resourceName: test.ner
```

### CODE REVIEW

**Comment by Gagravarr** [comment]
On the whole, we try to avoid raw un-prefixed metadata keys. We do have some, mostly older ones or ones from other standards, as you've seen! But ideally we try to use a prefix so that people know which standard to go check to understand what a key means. For example, we prefer `dc:title` to `title`, as the former makes it clearer what it means, the latter is now deprecated

Any chance you could replace keys like `ORGANIZATION` with something more like `prefix:name` based on a well-known external metadata definition? (May end up using multiple prefixes)

**Comment by TaichiHo** [comment]
Thank you for your suggestion. What do you think a good prefix would be like in this case?

The other thing is the way I integrate this might not possible due the GPL license, as is pointed out by https://issues.apache.org/jira/browse/TIKA-1787. I am not sure if I should continue work on this. 

The other issue is using a different approach. Might want to look at that. https://github.com/apache/tika/pull/61

**Comment by Gagravarr** [comment]
License wise, GPL dependencies are a no-go for ASF projects. You could maintain it independently though, but users would need to review the license and install manually if they were able to abide by the GPL restrictions. http://wiki.apache.org/tika/3rd%20party%20parser%20plugins is where we maintain the list of incompatibly licensed plugins

In terms of the prefix, I don't know, you're the expert in the tool rather than me! You'll need to read up the documentation from the tool, and find out from that what it means by the various outputs. If it defines them against a well known external standard, then great! Use that. If not, see if any well known metadata standards cover the same logical things, and map onto those

**Comment by TaichiHo** [comment]
Thanks so much.  I will look into it.

**Pull request closed without merging**
