### PR TITLE
TIKA-2293 - Tess4jOCRParser - A simpler Java version of TesseractOCRParser

### PR DESCRIPTION
**Pull request by ThejanW**
Right now, TesseractOCRParser calls tesseract and imagemagick from command line. Intention of this new parser "Tess4jOCRParser" is to use the Tess4J API instead of the runtime.exec way to executing tesseract out of process. Please feel free to visit TIKA-2293 for more information.

### CODE REVIEW

**Comment by rferreira** [comment]
hey folks, what's the good word on the PR? Seems like a reasonable improvement.

**Comment by tballison** [comment]
See the discussion here: https://issues.apache.org/jira/browse/TIKA-2293 .  I think there's consensus that this doesn't buy us enough and actually adds some complexity to our current setup.  I proposed moving this into a standalone project/parser that we can mention.

**Comment by rferreira** [comment]
ah makes sense, thanks!

**Comment by chrismattmann** [comment]
closing per comments from @tballison

**Comment by changetoblow** [comment]
Hello!I wonder why tess4jocrparser.java doesn't have this implementation in the current apache TIka version.thank you

**Comment by tballison** [comment]
This was my position 2 years ago: https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15939076&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15939076 

Let us know if anything has changed.

**Comment by tballison** [comment]
See also Luís Filipe Nassif's input: https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301

**Comment by changetoblow** [comment]
Thank you so much for your reply and advice.

**Comment by changetoblow** [comment]
> 另见LuísFilipeNassif的意见：[https](https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301)：//issues.apache.org/jira/browse/TIKA-2293？focusCommentId [=](https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301) 15943301 [＆](https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301) page [=](https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301) com.atlassian.jira.plugin.system.issuetabpanels：comment-tabpanel＃comment-15943301[](https://issues.apache.org/jira/browse/TIKA-2293?focusedCommentId=15943301&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15943301)
Hello!Tim, I have a project now, only need Apache Tika documents, pictures, videos of the three types of testing and analytical functions, but I see the Apache Tika has many modules, I want to know what these modules are job, and I want to put these function modules of the I don't have to out from Tika project, what should I do?I hope to get your help, thank you

**Comment by changetoblow** [comment]
Hello, I now use the tess4j API to identify images in Tika, and there is no problem when I only deal with images, but I have a problem when I deal with word file, because there are embedded images in the word file, and the error information is as follows:

`
17:33:28.423 [main] ERROR net.sourceforge.tess4j.Tesseract - Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.Tika.parseToString(Tika.java:608)
	at org.apache.tika.Tika.parseToString(Tika.java:723)
	at com.tika.test.tt.main(tt.java:20)
17:33:28.423 [main] WARN org.apache.tika.parser.ocr.TesseractOCRParser - java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
net.sourceforge.tess4j.TesseractException: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.Tika.parseToString(Tika.java:608)
	at org.apache.tika.Tika.parseToString(Tika.java:723)
	at com.tika.test.tt.main(tt.java:20)
Caused by: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214)
	... 20 common frames omitted
`
I have checked in two ways , first by using maven repository i.e


<dependency>
    <groupId>com.github.jai-imageio</groupId>
    <artifactId>jai-imageio-core</artifactId>
    <version>1.4.0</version>
</dependency>
Secondly , I have also checked by including the jar i.e jai-imageio-core-1.4.0.jar

In both ways I am getting the same error , how can I fix this?

**Comment by changetoblow** [comment]
17:33:28.423 [main] ERROR net.sourceforge.tess4j.Tesseract - Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.Tika.parseToString(Tika.java:608)
	at org.apache.tika.Tika.parseToString(Tika.java:723)
	at com.tika.test.tt.main(tt.java:20)
17:33:28.423 [main] WARN org.apache.tika.parser.ocr.TesseractOCRParser - java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
net.sourceforge.tess4j.TesseractException: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206)
	at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.Tika.parseToString(Tika.java:608)
	at org.apache.tika.Tika.parseToString(Tika.java:723)
	at com.tika.test.tt.main(tt.java:20)
Caused by: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214)
	... 20 common frames omitted

**Comment by changetoblow** [comment]
I found that the main reason for this problem was that when tika parsed the embedded image in word, it was finally parsed into a temporary file with the suffix of TMP and sent to tess4j for identification, which was not recognized by tess4j.So how to modify the type generated by tika to adapt to tess4j? Can you give me some ideas

**Pull request closed without merging**
