### PR TITLE
Allow tesseract/tessdata path to be specified by environment variables

### PR DESCRIPTION
**Pull request by peterkronenberg**

### CODE REVIEW

**Comment by lfcnassif** [comment]
I think this logic should be inverted to use ENV var if property or tesseractConfig object is not set in context. So global system configuration could be overridden by app specific configuration.

**Comment by peterkronenberg** [comment]
Hi, not sure I follow.   Are you saying TesseractConfig should override?  If the environment variable isn't set, then it will have the same behavior as before.  If you specify the env variables, than they will override

**Comment by lfcnassif** [comment]
Yes, inverting the logic, if tesseractPath (or tessdataPath) has the default empty value, env var would be used if set. If properties are specified, it will keep past behaviour too. I'm thinking about different apps in the same system using Tika, but with different configurations. Inverting the logic, it will not be an issue.

**Comment by peterkronenberg** [comment]
I think that's what it's already doing.  If you don't specify it in the config and it is specified in the environment, it will use the environment values.

**Comment by peterkronenberg** [comment]
So I think what you're saying is that even if environment variables are specified, then still use the config by default.  And only if config is blank, then use environment ?

**Comment by lfcnassif** [comment]
> So I think what you're saying is that even if environment variables are specified, then still use the config by default. And only if config is blank, then use environment ?

Yes that was my suggestion. Other commiter can have other opinion of course.

**Comment by peterkronenberg** [comment]
I just want to make sure that it doesn't break anything or have any unexpected behavior.  Let me try it your way and see how it works

**Comment by peterkronenberg** [comment]
Overtaken by events

**Pull request closed without merging**
