### PR TITLE
TIKA-4290: Need to use returned value of substring()

### PR DESCRIPTION
**Pull request by dk2k**
TIKA-4290: Need to use returned value of substring()

### CODE REVIEW

**Comment by THausherr** [comment]
There's a typo

**Comment by THausherr** [comment]
Do you have an example where this part of the code is used, i.e. did you hit a file where it happened? Or did you look at the source code and you or the IDE noticed the bug?

**Comment by dk2k** [comment]
@THausherr It's result of code inspection, I've got more to show in additional PRs.
I haven't hit this issue while using softaware.
Another option is to remove entire if {} as it has no effect

**Comment by THausherr** [comment]
Please include "TIKA-4290: " in front of your PR title, and further PRs that deal with bugs / real risks. Don't submit PRs about formatting or style issues or pet peeves. For some reason the boilerplate text didn't appear in your PR, see e.g. #1860. I've created https://issues.apache.org/jira/browse/TIKA-4290 for you.

**Pull request merged**
