### PR TITLE
fix for TIKA-2355 contributed by msharan@usc.edu

### PR DESCRIPTION
**Pull request by smadha**
Cache trained mode while running ObjectRecognition server from Docker builds

DockerBuilds of ObjectRecognition downloads model every time server starts. This can be prevented by initializing code once before we exit from DockerBuild so model is downloaded once and always available at sunsequent server startup

https://issues.apache.org/jira/browse/TIKA-2355

### CODE REVIEW

**Comment by ThejanW** [comment]
Will test this. Let's ask @thammegowda to merge this.

**Comment by smadha** [comment]
Looks like it will go in next release.

Thanks for testing, let us know the results on both Image and Video docker build

**Comment by ThejanW** [comment]
@chrismattmann @thammegowda I tested this. Can we quickly merge this? I gotta raise a PR with a few modifications to docker files.

**Comment by chrismattmann** [comment]
done @ThejanW !

**Comment by ThejanW** [comment]
thank you @chrismattmann :+1:

**Pull request merged**
