### PR TITLE
[TIKA-860] Allow for AutoDetectParser to specify SecureContentHandler parameters.

### PR DESCRIPTION
**Pull request by danielin917**
Previously TIKA-860 added getter and setters to make Zip bomb prevention
configuraable but because SecureContentHandler is create inline in
AutoDetectParser we have no access to these parameters.

This change adds a configuration object that can be set and used when
constructing the SecureContentHandler inline.

Thanks for your contribution to [Apache Tika](https://tika.apache.org/)! Your help is appreciated!

Before opening the pull request, please verify that
* there is an open issue on the [Tika issue tracker](https://issues.apache.org/jira/projects/TIKA) which describes the problem or the improvement. We cannot accept pull requests without an issue because the change wouldn't be listed in the release notes.
* the issue ID (`TIKA-XXXX`)
  - is referenced in the title of the pull request
  - and placed in front of your commit messages surrounded by square brackets (`[TIKA-XXXX] Issue or pull request title`)
* commits are squashed into a single one (or few commits for larger changes)
* Tika is successfully built and unit tests pass by running `mvn clean test`
* there should be no conflicts when merging the pull request branch into the *recent* `main` branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled `main` branch.

We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Tika in general, please sign up for the [Tika mailing list](http://tika.apache.org/mail-lists.html). Thanks!

### CODE REVIEW

**Comment by tballison** [comment]
I've been wanting to do something like this forever.  Thank you for opening this PR.  Two things: 1) main is our primary branch now (we've locked and no longer use master), 2) we should figure out how to add these configurations via tika-config.xml. 

If you change the target to `main`, I'll merge this and then try to figure out 2) unless you have any recs...

**Comment by tballison** [comment]
Oh, we should also add some unit tests...at some point.

**Comment by danielin917** [comment]
Works for me! Here's the PR on main: https://github.com/apache/tika/pull/456

**Comment by danielin917** [comment]
Merged into main

**Pull request closed without merging**
