### PR TITLE
[TIKA-4309] detailed Mach-O in tika-mimetypes.xml

### PR DESCRIPTION
**Pull request by alexey-pelykh**
A follow-up to #1947: Support 32-bit and 64-bit Mach-O files and detect their type

cc @tballison

### CODE REVIEW

**Comment by tballison** [comment]
Thanks to this, I learned about `type="host32"` and the others. Thank you! :D

**Comment by alexey-pelykh** [comment]
CI failure appears to be unrelated

**Comment by tballison** [comment]
Y, thank you. I just bumped protobuf on main. Let's hope the build works: https://github.com/apache/tika/actions/runs/10965546331

ossindex stopped complaining locally at least. :D

**Comment by alexey-pelykh** [comment]
Rebased the branch

**Pull request merged**
