### PR TITLE
WIP: TIKA-3164: POI 5.0.0

### PR DESCRIPTION
**Pull request by pjfanning**
https://issues.apache.org/jira/projects/TIKA/issues/TIKA-3164

### CODE REVIEW

**Comment by pjfanning** [comment]
@tballison I tried this on my laptop - the tika-parser microsoft tests passed but job later failed with

```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.181 s <<< FAILURE! - in org.apache.tika.parser.gdal.TestGDALParser
[ERROR] org.apache.tika.parser.gdal.TestGDALParser.testParseBasicInfo  Time elapsed: 12.795 s  <<< FAILURE!
java.lang.AssertionError
	at org.apache.tika.parser.gdal.TestGDALParser.testParseBasicInfo(TestGDALParser.java:82)
```

**Comment by tballison** [comment]
Sorry for my delay!  Not clear on why that test failed for you.  Let me take a look. Working on this today.

**Comment by tballison** [comment]
Aside from including the full schemas jar, is there a solution to this:
```[ERROR] Tests run: 13, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.548 s <<< FAILURE! - in org.apache.tika.parser.RecursiveParserWrapperTest
[ERROR] org.apache.tika.parser.RecursiveParserWrapperTest.testMaxEmbedded  Time elapsed: 0.16 s  <<< ERROR!
org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.ooxml.OOXMLParser@626c569b
	at org.apache.tika.parser.RecursiveParserWrapperTest.testMaxEmbedded(RecursiveParserWrapperTest.java:191)
Caused by: org.apache.xmlbeans.SchemaTypeLoaderException: XML-BEANS compiled schema: Could not locate compiled schema resource org/apache/poi/schemas/ooxml/system/ooxml/oleobjectelement.xsb (org.apache.poi.schemas.ooxml.system.ooxml.oleobjectelement) - code 0
	at org.apache.tika.parser.RecursiveParserWrapperTest.testMaxEmbedded(RecursiveParserWrapperTest.java:191)
```

**Comment by tballison** [comment]
See: https://github.com/apache/tika/tree/TIKA-3164-1.x

**Comment by tballison** [comment]
I'm adding "test_recursive_embedded.docx" to a unit test in POI locally to see if I can get it to add the oleobjectelement.xsb in schemas-lite.

**Comment by pjfanning** [comment]
there is the ooxml-schemas-full jar for cases where ooxml-schemas-lite is missing stuff

I thought all the xsb stuff was in ooxml-schemas-lite jar

definitely worth adding a test case to poi code base

POI 6.0.0 is probably going to be next release and it could be a couple of months (fairly big logging changes just merged and probably an uptake of a refactored xmlbeans jar)

**Comment by tballison** [comment]
Fresh checkout...

./gradlew build
Results:
```> Task :ooxml:compileJava
/home/tallison/Intellij/poi-trunk/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFCell.java:564: error: cannot access DocumentFactory
            f = CTCellFormula.Factory.newInstance();
                                     ^
  class file for org.apache.xmlbeans.impl.schema.DocumentFactory not found
/home/tallison/Intellij/poi-trunk/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFColor.java:117: error: recursive constructor invocation
    public XSSFColor(byte[] rgb, IndexedColorMap colorMap) {
           ^
/home/tallison/Intellij/poi-trunk/src/ooxml/java/org/apache/poi/xddf/usermodel/XDDFLineProperties.java:42: error: recursive constructor invocation
    public XDDFLineProperties(XDDFFillProperties fill) {
           ^
/home/tallison/Intellij/poi-trunk/src/ooxml/java/org/apache/poi/xddf/usermodel/text/XDDFHyperlink.java:29: error: recursive constructor invocation
    public XDDFHyperlink(String id) {
```

I'm guessing I need to run ant first to pull in the dependencies?

**Comment by pjfanning** [comment]
the gradle build depends quite a bit on the ant one - I would suggest getting ant build working and then the gradle build will probably start working

**Comment by tballison** [comment]
Uninstalled old ant
Installed new ant
```
ant -f fetch.xml -Ddest=system
```

```
echo ANT_HOME
/apache/apache-ant-1.10.9
```
```
ant -v
Apache Ant(TM) version 1.10.9 compiled on September 27 2020
```

ant clean test 

```BUILD FAILED
BUILD FAILED
/home/tallison/Intellij/poi-trunk/build.xml:1812: /home/tallison/Intellij/poi-trunk/build/ooxml-lite-report.clazz doesn't exist

Total time: 2 minutes 58 seconds

```

**Comment by tballison** [comment]
I'm sure the above is user error.  I've been away from POI for too long...argh...

**Comment by pjfanning** [comment]
@tballison would it be worth just using ooxml-schemas-full on tika - tika is big so the benefit of ooxml-schemas-lite is lower

**Comment by tballison** [comment]
I'm happy to do so for testing, but I'm hesitant to add even more to tika.  The point of 2.x is to modularize and make dependencies smaller.  I wouldn't rule it out, necessarily...

Any recs on the above build failure?  Thank you!

**Comment by pjfanning** [comment]
I'd suggest a clean checkout - there could be some stuff hanging around that `ant clean` is not removing

**Comment by tballison** [comment]
Clean checkout.

`ant compile` appears to work.

`ant test` fails with:

```test-main:
    [javac] Compiling 1 source file to /home/tallison/Intellij/poi-trunk/build/poi-ant-contrib

-test-main-write-testfile:

-test-scratchpad-check:

test-scratchpad-download-resources:

test-scratchpad:

-test-scratchpad-write-testfile:

-test-ooxml-check:

test-ooxml:

-test-ooxml-write-testfile:

compile-ooxml-lite:
     [echo] Create ooxml-lite schemas

BUILD FAILED
/home/tallison/Intellij/poi-trunk/build.xml:1812: /home/tallison/Intellij/poi-trunk/build/ooxml-lite-report.clazz doesn't exist
```

**Comment by pjfanning** [comment]
I'm not getting that issue - I'm using zulu jdk 11.0.7 and ant 1.10.8

**Comment by tballison** [comment]
K.  jdk 8 _should_ work, right?  I'll ping the dev list.  Thank you!

**Comment by pjfanning** [comment]
I made a mistake while building this. Looks like there are a few issues with the upgrade.

**Comment by tballison** [comment]
Y, see my branch.  We have to do a coupla handfuls of stuff on the tika side.

**Comment by tballison** [comment]
Please don't waste time on this...

**Pull request closed without merging**
