### PR TITLE
TIKA-1885 updates to tika-mimetypes.xml and custom detector for zero length files

### PR DESCRIPTION
**Pull request by adeshgupta**
TIKA- 1885 Updated mimetypes.xml file with *.cdf and *.xar files also, with a custom detector to detect zero length files. Also made enhancements to match patterns of video files and jpeg file formats.

### CODE REVIEW

**Comment by chrismattmann** [comment]
@adeshgupta you need to rebase this commit and get on 1.13 branch and make sure your PR only includes your changes. Please update.

**Comment by chrismattmann** [comment]
ping @adeshgupta

**Comment by adeshgupta** [comment]
Can you guide me on the 1.13 branch or is it the new master branch in this repo?
@chrismattmann , I am so sorry about the late reply

**Comment by chrismattmann** [comment]
Hi @adeshgupta you should simply rebase your local branch to apache/tika:master (git pull https://github.com/apache/tika.git master), and then handle any local conflicts, and then git push -u adeshgupta TIKA-1885)

**Comment by adeshgupta** [comment]
@chrismattmann , It has been done, Please review it and comment.

**Comment by chrismattmann** [comment]
Hi @adeshgupta this is closer. I can see in https://github.com/apache/tika/pull/89/commits/cdaccc5df7b1eb9eded45fe0578151ea43d33261 the actual change, but if you look at this pull request it includes 2600 *other* changes. I have no clue why this is. However if you can simply either update this or open up a new pull request that *only* includes those changes then it would be easier to review.

Some feedback:

1. https://github.com/apache/tika/pull/89/commits/cdaccc5df7b1eb9eded45fe0578151ea43d33261 doesn't include the actual MediaType.ZeroSize - where is this? 
2. ALv2 headers needed on detector.

**Comment by adeshgupta** [comment]
@chrismattmann , I have tried to remodify it again. The only problem I am facing right now is that the changes that were made were on tika 1.11 . Probably that is why it is showing so many changes to the files

**Comment by chrismattmann** [comment]
thanks @adeshgupta check your PR. Still 2k+ files changed. Try rebasing onto 1.13 master.

**Comment by adeshgupta** [comment]
@chrismattmann , I guess this should do it. around 200 files changed this time around, mostly are license additions/deletions. Will that be fine?

**Comment by chrismattmann** [comment]
Hi @adeshgupta the fix should simply be this. Can you try:

 1. git checkout -b fix-TIKA-1885 
 2. git pull https://github.com/apache/tika.git master
  [resolve conflicts locally, etc.]
 3. apply your edits e.g., make sure your single Detector is there, along with the tika-mimetypes.xml update and any other changes (should be ~2-3 files, right)
 4. commit and resolve everything locally
 5. git checkout TIKA-1885
 6. git reset --hard fix-TIKA-1885
 7. git push -u <your username> TIKA-1885

Try that.

**Comment by adeshgupta** [comment]
@chrismattmann , I have got down the changes to 63 files, I have only changed three files, but I have no clue why so many files are affected because of it

**Comment by chrismattmann** [comment]
OK @adeshgupta last try (it looks like your editor automatically reformatted these files in your latest PR since it just deletes them and adds them back). How about this. Can you:

1. Close this PR
2. Do a FRESH checkout of apache/tika from master
3. Make your 3 edits to the files in question
4. Submit a new PR based on that?

**Pull request closed without merging**
