### PR TITLE
Backport tika-langdetect from 2.x branch to 1.13 branch and Language Identification with Text Processing Toolkit from MITLL

### PR DESCRIPTION
**Pull request by trevorlewis**

### CODE REVIEW

**Comment by chrismattmann** [comment]
can you add ALv2 license headers seems like @kkrugler missed some license headers (e.g., in AbstractTranslator, etc.)

**Comment by kkrugler** [comment]
I've added the missing license headers (or at least the ones that I could find).

**Comment by trevorlewis** [comment]
I have added all the missing license headers.

**Comment by chrismattmann** [comment]
@trevorlewis @kkrugler, I have begun merging this and going to work on getting it into master. I'm running into an issue though. I've went ahead and merged the code from `trevorlewis:TIKA-1872` however, I get this error when running mvn install (after having fixed an error that referred in tika-langdetect to the 2.0-SNAPSHOT pom instead of the 1.13-SNAPSHOT.

```
[INFO] --- clirr-maven-plugin:2.6.1:check (default) @ tika-core ---
[ERROR] 8001: org.apache.tika.language.LanguageIdentifier: Class org.apache.tika.language.LanguageIdentifier removed
[ERROR] 8001: org.apache.tika.language.LanguageProfile: Class org.apache.tika.language.LanguageProfile removed
[ERROR] 8001: org.apache.tika.language.LanguageProfilerBuilder: Class org.apache.tika.language.LanguageProfilerBuilder removed
[ERROR] 8001: org.apache.tika.language.ProfilingHandler: Class org.apache.tika.language.ProfilingHandler removed
[ERROR] 8001: org.apache.tika.language.ProfilingWriter: Class org.apache.tika.language.ProfilingWriter removed
```

Do you know what this error is?

**Comment by chrismattmann** [comment]
you should be able to reproduce the error by looking at https://github.com/chrismattmann/tika/tree/TIKA-1872/

**Comment by kkrugler** [comment]
Those classes have moved and/or been renamed in 2.0, so the clirr plugin is complaining.

**Comment by chrismattmann** [comment]
How do I fix it @kkrugler

**Comment by kkrugler** [comment]
There's discussion about this in comments on https://issues.apache.org/jira/browse/TIKA-1723. Easiest is to just keep the current detection code as-is, and flag with deprecated annotations. More ambitious would be to turn some (most?) of these classes into facades, that call through to the (new architecture) language detection code, which for 1.x would be a port of the current detector.

**Comment by chrismattmann** [comment]
Ken I'm dense I don't see this error mentioned there

**Comment by kkrugler** [comment]
The discussion I referenced was about removing the old language detection support. Removing these classes is what triggers the errors you are getting from the clirr plugin, as it (correctly) reports that some public APIs (from the previous release) are no longer available.

**Comment by chrismattmann** [comment]
Got it so how are you making it build on 2.x? What do I do to get it to proceed?

**Comment by kkrugler** [comment]
For the 2.0 build, we disabled the clirr check (in tika-core/pom.xml), since we were busy breaking the API.

As far as how to proceed - well, if we still want no breaking API changes in the 1.x branch, then you'd need to do what I'd mentioned in my earlier comment:

> Easiest is to just keep the current detection code as-is, and flag with deprecated annotations. More ambitious would be to turn some (most?) of these classes into facades, that call through to the (new architecture) language detection code, which for 1.x would be a port of the current detector.

**Comment by chrismattmann** [comment]
got it, that helps a lot, @kkrugler thanks

**Comment by trevorlewis** [comment]
@chrismattmann I fixed the Clirr error by excluding checking the previous language detector classes for compatibility. I can add the old classes back if needed.
Also, I updated the TextLangDetector class to use WebClient and Response to make the GET and PUT requests to the server.

**Comment by chrismattmann** [comment]
Yes please update the PR thanks Trevor

**Comment by trevorlewis** [comment]
@chrismattmann I updated the PR

**Comment by chrismattmann** [comment]
@trevorlewis this worked great!

```
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ tika ---
[INFO] Installing /Users/mattmann/tmp/tika1.13/pom.xml to /Users/mattmann/.m2/repository/org/apache/tika/tika/1.13-SNAPSHOT/tika-1.13-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Tika parent ................................. SUCCESS [  1.115 s]
[INFO] Apache Tika core ................................... SUCCESS [  9.602 s]
[INFO] Apache Tika parsers ................................ SUCCESS [01:29 min]
[INFO] Apache Tika XMP .................................... SUCCESS [  1.748 s]
[INFO] Apache Tika serialization .......................... SUCCESS [  1.401 s]
[INFO] Apache Tika batch .................................. SUCCESS [01:48 min]
[INFO] Apache Tika language detection ..................... SUCCESS [  3.461 s]
[INFO] Apache Tika application ............................ SUCCESS [ 31.432 s]
[INFO] Apache Tika OSGi bundle ............................ SUCCESS [ 19.109 s]
[INFO] Apache Tika translate .............................. SUCCESS [  1.899 s]
[INFO] Apache Tika server ................................. SUCCESS [ 40.699 s]
[INFO] Apache Tika examples ............................... SUCCESS [ 13.093 s]
[INFO] Apache Tika Java-7 Components ...................... SUCCESS [  1.913 s]
[INFO] Apache Tika ........................................ SUCCESS [  0.023 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:23 min
[INFO] Finished at: 2016-04-22T15:01:08-07:00
[INFO] Final Memory: 130M/1683M
[INFO] ------------------------------------------------------------------------
```

I'm going to merge this now.

**Pull request merged**
