### PR TITLE
TIKA-3347 -- upgrade to PDFBox 3.x

### PR DESCRIPTION
**Pull request by tballison**
Thanks for your contribution to [Apache Tika](https://tika.apache.org/)! Your help is appreciated!

Before opening the pull request, please verify that
* there is an open issue on the [Tika issue tracker](https://issues.apache.org/jira/projects/TIKA) which describes the problem or the improvement. We cannot accept pull requests without an issue because the change wouldn't be listed in the release notes.
* the issue ID (`TIKA-XXXX`)
  - is referenced in the title of the pull request
  - and placed in front of your commit messages surrounded by square brackets (`[TIKA-XXXX] Issue or pull request title`)
* commits are squashed into a single one (or few commits for larger changes)
* Tika is successfully built and unit tests pass by running `mvn clean test`
* there should be no conflicts when merging the pull request branch into the *recent* `main` branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled `main` branch
* if you add new module that downstream users will depend upon add it to relevant group in `tika-bom/pom.xml`.

We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Tika in general, please sign up for the [Tika mailing list](http://tika.apache.org/mail-lists.html). Thanks!

### CODE REVIEW

**Comment by tballison** [comment]
Until PDFBox 3.0.1 is released, this requires a local build of PDFBox. I'll move this out of draft stage once PDFBox is released.

**Comment by danielstravito** [comment]
@tballison Will this be backported to Tika 2.x, or if not, how far off is Tika 3.x?

**Comment by dsvensson** [comment]
@tballison Will this be backported to Tika 2.x, or if not, how far off is Tika 3.x?

**Comment by tballison** [comment]
I just asked on our dev list. I'd like to get 3.x out soon. We need a beta2 release, though, I think.

**Comment by kbachuHighSpot** [comment]
This is great. Thanks for working on this.
Is this released with 3.0.0 thats in Beta? Because its listed here - https://tika.apache.org/3.0.0-BETA/index.html

We are blocked on upgrading `pdfbox` to `3.0.2` because we also use `tika 1.24` that is not compatible with `pdfbox 3.0.2`.

I just tried upgrading `tika` to 3.0.0(Beta), I am still getting the error.
```
Execution error (NoSuchMethodError) at org.apache.tika.parser.pdf.PDFParser/getPDDocument (PDFParser.java:506).
'org.apache.pdfbox.pdmodel.PDDocument org.apache.pdfbox.pdmodel.PDDocument.load(java.io.File, java.lang.String, org.apache.pdfbox.io.MemoryUsageSetting)'
```

**Comment by tballison** [comment]
Y, it should have been in 3.0.0-BETA.  How are you using it?

**Comment by kbachuHighSpot** [comment]
Sorry, I cannot use 3.0.0-BETA, I can only use 2.9.2.
```
<dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-parsers-standard-package</artifactId>
      <version>2.9.2</version>
    </dependency>
```
Is there a way to use latest beta version for testing?

**Comment by kbachuHighSpot** [comment]
I tried using `3.0.0-SNAPSHOT` in `.pom` file but can't find it.

```
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in clojars (https://repo.clojars.org/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in maven.alfresco.com (https://maven.alfresco.com/nexus/content/groups/public/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in clojars (https://repo.clojars.org/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in maven.alfresco.com (https://maven.alfresco.com/nexus/content/groups/public/)
```

**Comment by kbachuHighSpot** [comment]
I was able to use tika `3.0.0-BETA` and the `pdfbox` is at `3.0.2`.

Seeing this issue - any ideas? am I missing anything?

```
java.io.IOException: Invalid character code 0xD800
	at org.apache.fontbox.ttf.CmapSubtable.processSubtype13(CmapSubtable.java:320)
	at org.apache.fontbox.ttf.CmapSubtable.initSubtable(CmapSubtable.java:113)
	at org.apache.fontbox.ttf.CmapTable.read(CmapTable.java:87)
	at org.apache.fontbox.ttf.TrueTypeFont.readTable(TrueTypeFont.java:365)
	at org.apache.fontbox.ttf.TTFParser.parseTables(TTFParser.java:165)
	at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:144)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:56)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:27)
	at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:66)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:50)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.addTrueTypeFont(FileSystemFontProvider.java:684)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.scanFonts(FileSystemFontProvider.java:390)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java:365)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java:139)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java:158)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java:410)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getTrueTypeFont(FontMapperImpl.java:318)
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:142)
	at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:153)
	at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:170)
	at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:72)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:893)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:531)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:506)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:153)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:153)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:362)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:137)
	at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1369)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:235)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:108)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:215)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
	at com.xxx.content.Tika.extract(Tika.java:49)
	at com.xxx.content.Tika.extractText(Tika.java:33)
```

**Comment by THausherr** [comment]
Please look at the rest of the log output. IIRC this is a problem with `lastresortfont.otf` when the initial scanning is done. But that font is skipped and life continues.

**Comment by kbachuHighSpot** [comment]
yeah, I see. There are more of these. Since `ioexception` is thrown, we are failing. Is there anything I can do to avoid these errors? why are they occuring?


```
23:32:53.243 WARN i[Content] [main] j[6685831e5864fc77b5140f4a] o.a.p.p.f.FileSystemFontProvider 368 new fonts found, font cache will be re-built
23:32:53.243 WARN i[Content] [main] j[6685831e5864fc77b5140f4a] o.a.p.p.f.FileSystemFontProvider Building on-disk font cache, this may take a while
23:32:54.101 WARN i[Content] [main] j[6685831e5864fc77b5140f4a] o.a.p.p.f.FileSystemFontProvider Could not load font file: /System/Library/Fonts/LastResort.otf
```

```
23:32:55.670 WARN i[Content] [main] j[6685831e5864fc77b5140f4a] o.a.p.p.f.FileSystemFontProvider Could not load font file: /System/Library/Fonts/Supplemental/NISC18030.ttf
java.io.IOException: 'head' table is mandatory
```

**Comment by THausherr** [comment]
There has been a complaint about the NISC18030.ttf font in the past: PDFBOX-5743, and I can see in the browser that I searched for it and found it at https://github.com/justrajdeep/fonts/blob/master/NISC18030.ttf , and another complaint at https://github.com/XQuartz/XQuartz/issues/304 . I downloaded it again and there is indeed no "head" table. (And no glyf table either). It does have a name table and the font is "GB18030 Bitmap". The failure (i.e. that the entire scan fails) has been fixed some time ago, definitively in 3.0.2.

**Comment by kbachuHighSpot** [comment]
Thank you @THausherr.
These errors are occuring for a bad pdf file. Even with these errors ignoring and repairing, we are able to process it fine now.

Any idea when we plan to release this TIKA version?

Until its released, how can I pull from snapshots? https://github.com/apache/tika/pull/1473#issuecomment-2207307712

**Comment by THausherr** [comment]
There's been plans to do another alpha soon. Snapshots are here:
https://repository.apache.org/content/groups/snapshots/org/apache/tika/tika-app/3.0.0-SNAPSHOT/

**Comment by kbachuHighSpot** [comment]
But which repo should I point to in `.pom` file?

I tried using 3.0.0-SNAPSHOT or 3.0.0 in .pom file but can't find it.

```
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in clojars (https://repo.clojars.org/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Could not find artifact org.apache.tika:tika-core:jar:3.0.0 in maven.alfresco.com (https://maven.alfresco.com/nexus/content/groups/public/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in clojars (https://repo.clojars.org/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/)
Could not find artifact org.apache.tika:tika-parsers-standard-package:jar:3.0.0 in maven.alfresco.com (https://maven.alfresco.com/nexus/content/groups/public/)
```

**Comment by THausherr** [comment]
It's not in maven central. Add this to your pom.xml
```
<repositories>
        <repository>
            <id>id1</id>
            <url>https://repository.apache.org/snapshots/</url>
        </repository>        
        <repository>
            <id>id2</id>
            <url>https://repository.apache.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by kbachuHighSpot** [comment]
Thank you @tballison . This worked. However, we have a lot of dependencies on the version to be a release.
Any idea when new TIKA version be released? just so that we can put it in the plan to upgrade Tika to a new release that is compatible with pdfbox 3.x.

**Comment by kbachuHighSpot** [comment]
I had to revert to `3.0.0-BETA` instead of `3.0.0-SNAPSHOT` due to dependencies in our code.

Running into this issue when I use `BETA` version. 

```

[2024-07-08T22:29:48Z] Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:476).
[2024-07-08T22:29:48Z] org.apache.tika.metadata.TikaMetadataKeys

```

I am using -
```
<groupId>org.apache.tika</groupId>
      <artifactId>tika-core</artifactId>
      <version>3.0.0-BETA</version>
<groupId>org.apache.tika</groupId>
      <artifactId>tika-parsers-standard-package</artifactId>
      <version>3.0.0-BETA</version>
```

**Comment by THausherr** [comment]
Try `TikaCoreProperties` instead.

**Comment by kbachuHighSpot** [comment]
Thank you. That worked but I bumped into a new issue now after working through few other huccups. 
I am trying to parse a ppt file.

```
import org.apache.tika.io.TikaInputStream;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.parser.AutoDetectParser;
import org.apache.tika.parser.ParseContext;
import org.apache.tika.parser.Parser;
import org.apache.tika.sax.BodyContentHandler;
import org.apache.tika.sax.OfflineContentHandler;
import org.apache.tika.parser.ocr.TesseractOCRConfig;

    TesseractOCRConfig config = new TesseractOCRConfig();
    config.setSkipOcr(true);
    ParseContext context = new ParseContext();
    context.set(TesseractOCRConfig.class, config);

    Parser parser = new AutoDetectParser();
    Metadata metadata = new Metadata();
    OfflineContentHandler handler = new OfflineContentHandler(new BodyContentHandler(writer));

    // Note: here we have to use TikaInputStream.get, otherwise certain content type (e.g. 2007
    // pptx) might not be correctly detected by the parser
    try (InputStream original = TikaInputStream.get(input, metadata)) {
      parser.parse(original, handler, metadata, context); 
                 ==> Above call is crashing with
        Execution error (NoSuchMethodError) at org.apache.poi.util.IOUtils/toByteArray (IOUtils.java:241).
'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
    }
```

**Comment by THausherr** [comment]
It worked for me with small changes because your code isn't runnable:

```
        Path input = Paths.get("samplepptx.pptx");
        Writer writer = new OutputStreamWriter(System.out);
```        
The file is
https://scholar.harvard.edu/files/torman_personal/files/samplepptx.pptx

Maybe you have another commons-io dependency in your pom.xml. Use this:

```
    <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.16.1</version>
    </dependency>
```

Use the maven versions plugin to check that you're up-to-date:
```

<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>versions-maven-plugin</artifactId>
    <executions>
        <execution>
            <phase>install</phase>
            <goals>
                <goal>display-plugin-updates</goal>
                <goal>display-dependency-updates</goal>
                <goal>display-property-updates</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <verbose>true</verbose>
        <allowSnapshots>false</allowSnapshots>
    </configuration>
</plugin>
```

My output:

Sample PowerPoint File
St. Cloud Technical College


This is a Sample Slide
Here is an outline of bulleted points
You can print out PPT files as handouts using the 
PRINT > 
  PRINT WHAT > HANDOUTS option


image2.jpeg

image1.jpeg

**Comment by THausherr** [comment]
This is really getting off-topic, please post to the tika users mailing list (don't forget to subscribe)
https://lists.apache.org/list.html?user@tika.apache.org    see bottom left
or ask on stackoverflow

**Comment by kbachuHighSpot** [comment]
Will do. Thank you for the help.

With the above `commons-io` suggestion, everything looks good now. Will be doing more testing.

**Comment by dsvensson** [comment]
@tballison Been a while since BETA2 got tagged now. Is there any list of blockers, or is there any plan on backporting PDFBox 3.x to Tika 2.x?

**Comment by THausherr** [comment]
Yes (something with tika pipes / grpc), and no. PDFBox 2 is similar in text extraction, it just has a higher memory footprint.

**Comment by tballison** [comment]
Thread here: https://lists.apache.org/thread/061nr8q9c38tn935krl8fldcs789gnqr

**Pull request merged**
