### PR TITLE
Fix can't del tmp file in windows

### PR DESCRIPTION
**Pull request by PeterAlfredLee**
TestCase `org.apache.tika.image.HeifParserTest.testSimple` failed in windows because `TemporaryResources.close()` sometimes fail to delete tmp file.

We can make it `deleteOnExit` as it's only a temp file, as Windows will eventually delete them from time to time even through `deleteOnExit` failed.

### CODE REVIEW

**Comment by THausherr** [comment]
Isn't this moot?
https://issues.apache.org/jira/browse/TIKA-3135

**Comment by PeterAlfredLee** [comment]
Hi @THausherr , sorry for the late reply.
I think the fix in [TIKA-3135](https://issues.apache.org/jira/browse/TIKA-3135) is trying to avoid occupying the file, therefore we can close it(mostly on Windows).
My fix in this PR is trying to make the file deleteOnExit in exception handle, and they will be eventually deleted. Considering they are temp files, I think this fix is reasonable - we do not need to stop the process if exceptions are thrown when deleting temp files.

**Comment by THausherr** [comment]
I agree that it shouldn't stop the process. Suggestion: output a log message, because the cause is usually a programming oversight, so that it can be reported and fixed.

**Comment by PeterAlfredLee** [comment]
> Suggestion: also output a log message, because the cause is usually a programming oversight, so that it can be reported and fixed.

Just pushed the logging part. :)

**Pull request merged**
