### PR TITLE
Updated Object Recognition Parser from Inception v3 to Inception v4. …

### PR DESCRIPTION
**Pull request by raunaqabhyankar**
…Changed classify_image.py and added Inception v4 dependencies in ./tensorflow

New files are added because Inception_v4 is packaged as a checkpoint (.ckpt) and not a protobuf graph. (Unlike the earlier Inception v3)

### CODE REVIEW

**Comment by thammegowda** [comment]
Reviewing this today.

**Comment by thammegowda** [comment]
@raunaqabhyankar Thanks for the PR! We appreciate your efforts.

As you see this is a duplicate effort of #163, so we can merge only one of these PRs.

It looks to me that #163 is providing a full upgrade from V3 to V4 which includes:
-  Command Line Tool (classify_image.py)
- Rest API
- Docker file.

This PR provides only upgrades the Command Line Tool (classify_image.py).
Please collaborate your efforts on #163

**Comment by thammegowda** [comment]
We shall close this PR and instead focus efforts for merging #163  if other reviewers agree with me.

**Comment by KranthiGV** [comment]
@raunaqabhyankar 
As far as collaboration is concerned, #163 closes TIKA-2306 once merged.
So, we can work on [TIKA-2324](https://issues.apache.org/jira/browse/TIKA-2324) to provide support for all image MIME types. Let me know if you are interested.

**Pull request closed without merging**
