### PR TITLE
[TIKA-4283] - Implemented support for JKS Java Keystore format

### PR DESCRIPTION
**Pull request by Lonzak**
Thanks for your contribution to [Apache Tika](https://tika.apache.org/)! Your help is appreciated!

Before opening the pull request, please verify that
* there is an open issue on the [Tika issue tracker](https://issues.apache.org/jira/projects/TIKA) which describes the problem or the improvement. We cannot accept pull requests without an issue because the change wouldn't be listed in the release notes.
* the issue ID (`TIKA-XXXX`)
  - is referenced in the title of the pull request
  - and placed in front of your commit messages surrounded by square brackets (`[TIKA-XXXX] Issue or pull request title`)
* commits are squashed into a single one (or few commits for larger changes)
* Tika is successfully built and unit tests pass by running `mvn clean test`
* there should be no conflicts when merging the pull request branch into the *recent* `main` branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled `main` branch
* if you add new module that downstream users will depend upon add it to relevant group in `tika-bom/pom.xml`.

We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Tika in general, please sign up for the [Tika mailing list](http://tika.apache.org/mail-lists.html). Thanks!

### CODE REVIEW

**Comment by Lonzak** [comment]
It would be highly appreciated if this feature could be added (also) to the 2.9.X branch - thank you.

**Comment by tballison** [comment]
ossindex failed with on cxf. Any chance you can merge from main to upgrade to 4.0.5? Thank you!

**Comment by THausherr** [comment]
@Lonzak your fork is 12 commits behind, cxf was updated recently.

**Comment by tballison** [comment]
It is weird to me (but shouldn't be?!) that the action is running against the fork and not against our main with the PR applied.

**Comment by THausherr** [comment]
Now it's green.

**Comment by Lonzak** [comment]
Merged it. 
Regarding the branch - should I have done the changes on branch_2x instead?

**Comment by THausherr** [comment]
No it's fine, we can do this after the main merge.

**Pull request merged**
