### PR TITLE
TIKA-3446 - 1.x port of TIKA-3446 - Support for parsing OneNote when Alternative Encoding Using the File Synchronization via SOAP Over HTTP Protocol

### PR DESCRIPTION
**Pull request by nddipiazza**
Porting https://github.com/apache/tika/pull/461 to Tika 1.x

### CODE REVIEW

**Comment by nddipiazza** [comment]
@tballison am I OK to use stringutils3 in the 1.x branch?

**Comment by tballison** [comment]
@nddipiazza I think the goal is to keep tika-core as slim as possible, but you can put whatever you need in tika-parsers, as long as we don't have any conflicts.

**Comment by nddipiazza** [comment]
OK @tballison got a moment for a quick review on this one? Is this OK to add into the upcoming 1.x release?

**Comment by tballison** [comment]
Looks good to me.  Y, go for it.

**Pull request merged**
