### PR TITLE
fix for TIKA-1943 contributed by Mark Duske

### PR DESCRIPTION
**Pull request by reevapp**
Includes support for Yandex Translate API

### CODE REVIEW

**Comment by chrismattmann** [comment]
hey @reevapp - do you know who I can get in touch with at Yandex for a key that I could use for research purposes to get beyond API limits? I'm doing research and writing papers in this area and would love to add Yandex to my existing Lingo24, Bing, Google Translate, and Joshua comparisons. chris.mattmann@gmail.com is my email and can contact me there.

**Comment by reevapp** [comment]
Hi, the access is free for small projects:
"Developers of small translation projects, which do not exceed 10,000,000 characters a month (and no more than 1,000,000 in 24 hours), can use the Yandex.Translate API for free." - https://translate.yandex.com/developers

You can get a API Key for free here: https://tech.yandex.com/translate/

**Comment by chrismattmann** [comment]
Yeah I am doing much more than that so looking for a research oriented key but for big data do you have a contact there?

**Comment by reevapp** [comment]
Nope, no contact there... I just needed a good translation engine for a small open source project and found their service.

**Pull request closed without merging**
