### PR TITLE
TIKA-3039 Remove dockerfile:build mvn goal

### PR DESCRIPTION
**Pull request by epugh**
Per mailing list discussion, remove mvn goal.

### CODE REVIEW

**Comment by epugh** [comment]
@dameikle any chance of a review?

**Comment by tballison** [comment]
@dameikle unless you have objections, I'll merge this shortly?

**Comment by tballison** [comment]
@epugh would you mind fixing the conflicts...sorry!

**Comment by epugh** [comment]
Okay @tballison it was a small chagne, ready for merge.

**Comment by tballison** [comment]
Thank you!

**Pull request merged**
