### PR TITLE
Tika NER implementation that invokes Grobid Quantities via a REST service.

### PR DESCRIPTION
**Pull request by AravindRam**
Hi Professor @chrismattmann ,

I have implemented the Grobid NER and integrated it with Tika. Grobid Quantities can now be used as a REST service from Tika. Please check and let me know if it is fine or if any changes have to be made.

Thanks

### CODE REVIEW

**Comment by yashtanna93** [comment]
@chrismattmann I have sent a pull request to @AravindRam for the fixes

**Comment by chrismattmann** [comment]
looks great going to merge this now. Guys, please follow the process listed at: http://github.com/apache/tika/#contributing-via-github in the future and create a JIRA ticket to accompany this. @AravindRam @yashtanna93

**Comment by AravindRam** [comment]
Hi Professor @chrismattmann 

Here is the link to the documentation for running Grobid Quantities as a REST service. 
http://wiki.apache.org/tika/GrobidQuantitiesParser . It has already been merged into the Tika Wiki Page. 

Thanks

**Comment by lfoppiano** [comment]
👍 Very nice job guys!! 💯

**Pull request merged**
