### PR TITLE
Changed matching of node(), support for descendant-or-self 

### PR DESCRIPTION
**Pull request by WulfB**

### CODE REVIEW

**Comment by chrismattmann** [comment]
Hi @WulfB can you suggest what this PR addresses? What problem does it address?

**Comment by WulfB** [comment]
Hi Chris, yes of course:

following the w3c spec the xpath node test ./node() should matches all contained nodes (types) but not attributes since attributes are no children. (=> Changes in NodeMatcher)

So "/node()" returns a superset of "/*". In XPathParser the latter lead to the construction of "ChildMatcher(parse(xpath.substring(2)));" but the first simply returned a "NodeMatcher.INSTANCE" what is wrong i.m.o.

**Comment by chrismattmann** [comment]
Got it. Would you be willing to file a tika jira issue to go with this request?

**Comment by chrismattmann** [comment]
hi @WulfB - I think this broke the build, can you see: https://builds.apache.org/job/tika-trunk-jdk1.7/771/ and take a look at the now failing tests?

**Comment by chrismattmann** [comment]
For now, I've rolled it back until we figure it out:

```
[chipotle:~/tmp/tika1.10] mattmann% svn commit -m "Rollback r1688087 as it seems to cause some tests to fail."
Sending        CHANGES.txt
Sending        tika-core/src/main/java/org/apache/tika/sax/xpath/NodeMatcher.java
Sending        tika-core/src/main/java/org/apache/tika/sax/xpath/XPathParser.java
Sending        tika-core/src/test/java/org/apache/tika/sax/xpath/XPathParserTest.java
Transmitting file data ....
Committed revision 1688239.
[chipotle:~/tmp/tika1.10] mattmann% 
```

**Comment by WulfB** [comment]
Hi Chris, I’ll try to have a look on it tomorrow morning. See you, Wulf.

Von: Chris Mattmann [mailto:notifications@github.com]
Gesendet: Montag, 29. Juni 2015 16:09
An: apache/tika
Cc: Wulf Berschin
Betreff: Re: [tika] Changed matching of node(), support for descendant-or-self (#52)


hi @WulfB<https://github.com/WulfB> - I think this broke the build, can you see: https://builds.apache.org/job/tika-trunk-jdk1.7/771/ and take a look at the now failing tests?

**Pull request closed without merging**
