### PR TITLE
Fix for TIKA-2955 filter out invalid HTML characters 0x7F to 0x9F

### PR DESCRIPTION
**Pull request by LukeButters**

### CODE REVIEW

**Comment by LukeButters** [comment]
@tballison the PR for the invalid HTML chars

**Comment by LukeButters** [comment]
thanks Tim. Do I now need to do something to cherrypick it into a some 1.X version?

**Comment by tballison** [comment]
I took care of it in branch_1x. You’ve done plenty. Thank you!

**Comment by LukeButters** [comment]
ah neat, does a date exist for when that will be released?

**Pull request merged**
