### PR TITLE
fix for TIKA-1943 contributed by Mark Duske

### PR DESCRIPTION
**Pull request by reevapp**
Properties file used by YandexTranslator

### CODE REVIEW

**Comment by tpalsulich** [comment]
Did you happen to forget to add the Translator implementation?

**Comment by reevapp** [comment]
did 3 Pulls requests... all with the same title "fix for TIKA-1943 contributed by Mark Duske", the others have the implementation.

**Comment by tpalsulich** [comment]
Would you mind consolidating the pull requests into a single one? It will be easier to review, test, and merge. Thank you!

**Comment by reevapp** [comment]
No problem, I am closing the original pull requests and submitting a single pull with all 3 files

**Pull request closed without merging**
